"""Conversation mode: the actor talks, one world turn at a time.

A conversation is a world object with a seat for up to four settlers and a
round-robin turn order (docs/09_conversation_and_reflex.md section 2). While
the actor holds a seat, `ConversationSession` owns its body.

Inside the package: `protocol` (action names, end reasons, call shapes),
`converser` (the two model agents and the timed call), `report` (what the
planner reads afterwards) and `session` (the tick-by-tick machine).
"""

from __future__ import annotations

from .converser import (
    CONVERSER_NARRATIVE,
    NOTE_INSTRUCTION,
    ModelConverser,
    converser_narrative,
    run_converser,
)
from .protocol import (
    ACTION_EAT,
    ACTION_GIVE,
    ACTION_HAIL,
    ACTION_HAILED,
    ACTION_JOIN,
    ACTION_LEAVE,
    ACTION_OPEN,
    ACTION_PASS,
    ACTION_SPEAK,
    CONVERSER_TIMEOUT_SECONDS,
    CONVERSE_ACTION_TYPE,
    DUPLICATE_TICK_WINDOW,
    EAT_ACTION_TYPE,
    END_ASLEEP,
    END_CLOSED,
    END_DIED,
    END_LEFT,
    END_NEW_MOON,
    END_NOBODY_JOINED,
    END_REMOVED,
    GIVE_ACTION_TYPE,
    JOIN_ACTIONS,
    MAX_NOTE_CHARACTERS,
    MOVE_ACTION_TYPES,
    NOTE_STALE,
    NO_MOVE_ACTION,
    OBJECT_GRACE_TICKS,
    OUTCOME_NOT_CARRIED_OUT,
    OUTCOME_NO_KIND,
    OUTCOME_NO_TARGET,
    SLEEP_END_TEXT,
    UNASKED_VIA,
    VIA_HAILED,
    CallResult,
    ClosingNote,
    Converser,
    ConverserMove,
    MoveCall,
    MoveOutcome,
    NoteCall,
    PendingCall,
)
from .report import ConversationReport, sleep_end_reason
from .session import (
    ApproachDriver,
    ConversationSession,
    append_conversation_note,
    describe_move,
    free_seat_tiles,
    joined_conversation,
    joined_conversation_id,
    merge_transcript,
    read_notes,
    transcript_for,
)

__all__ = [
    "ACTION_EAT",
    "ACTION_GIVE",
    "ACTION_HAIL",
    "ACTION_HAILED",
    "ACTION_JOIN",
    "ACTION_LEAVE",
    "ACTION_OPEN",
    "ACTION_PASS",
    "ACTION_SPEAK",
    "ApproachDriver",
    "CONVERSER_NARRATIVE",
    "CONVERSER_TIMEOUT_SECONDS",
    "CONVERSE_ACTION_TYPE",
    "CallResult",
    "ClosingNote",
    "ConversationReport",
    "ConversationSession",
    "Converser",
    "ConverserMove",
    "DUPLICATE_TICK_WINDOW",
    "EAT_ACTION_TYPE",
    "END_ASLEEP",
    "END_CLOSED",
    "END_DIED",
    "END_LEFT",
    "END_NEW_MOON",
    "END_NOBODY_JOINED",
    "END_REMOVED",
    "GIVE_ACTION_TYPE",
    "JOIN_ACTIONS",
    "MAX_NOTE_CHARACTERS",
    "MOVE_ACTION_TYPES",
    "ModelConverser",
    "MoveCall",
    "MoveOutcome",
    "NOTE_INSTRUCTION",
    "NOTE_STALE",
    "NO_MOVE_ACTION",
    "NoteCall",
    "OBJECT_GRACE_TICKS",
    "OUTCOME_NOT_CARRIED_OUT",
    "OUTCOME_NO_KIND",
    "OUTCOME_NO_TARGET",
    "PendingCall",
    "SLEEP_END_TEXT",
    "UNASKED_VIA",
    "VIA_HAILED",
    "append_conversation_note",
    "converser_narrative",
    "describe_move",
    "free_seat_tiles",
    "joined_conversation",
    "joined_conversation_id",
    "merge_transcript",
    "read_notes",
    "run_converser",
    "sleep_end_reason",
    "transcript_for",
]
