/**
 * Types and utilities for loading sprites from the sprite index.
 * The sprite index is generated by tools/generate_sprite_index.py from Tiled TSX files.
 */

export interface AnimationFrame {
  spritesheet: string;
  frame: number;
}

export interface SpriteEntry {
  spritesheet: string;
  frame: number;
  columns: number;
  animationFrames?: AnimationFrame[];
}

export type SpriteIndex = Record<string, SpriteEntry>;

/**
 * Converts a spritesheet path from the index format to a Phaser key.
 * Example: "Characters/Player0.png" -> "Characters-Player0"
 */
export function spritesheetToKey(spritesheet: string): string {
  return spritesheet.replace(/\//g, '-').replace('.png', '');
}

/**
 * Gets all unique spritesheets referenced in the sprite index.
 */
export function getUniqueSpritesheets(index: SpriteIndex): string[] {
  const sheets = new Set<string>();
  for (const entry of Object.values(index)) {
    sheets.add(entry.spritesheet);
    if (entry.animationFrames) {
      for (const frame of entry.animationFrames) {
        sheets.add(frame.spritesheet);
      }
    }
  }
  return Array.from(sheets);
}

/**
 * Gets the Phaser texture key and frame for a sprite by its key.
 */
export function getSpriteFrame(
  index: SpriteIndex,
  key: string
): { textureKey: string; frame: number } | null {
  const entry = index[key];
  if (!entry) return null;
  return {
    textureKey: spritesheetToKey(entry.spritesheet),
    frame: entry.frame,
  };
}

/**
 * Gets animation frame data for a sprite, if it has animation frames.
 */
export function getAnimationFrames(
  index: SpriteIndex,
  key: string
): Array<{ key: string; frame: number }> | null {
  const entry = index[key];
  if (!entry?.animationFrames || entry.animationFrames.length === 0) return null;

  return entry.animationFrames.map((af) => ({
    key: spritesheetToKey(af.spritesheet),
    frame: af.frame,
  }));
}
