[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tim Garvin", email = "tcgarvin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bobgame-rules",
    "pillow>=12.1.0",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[tool.uv.sources]
bobgame-rules = { path = "../rules", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
