# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import world_pb2 as world__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in world_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TickServiceStub(object):
    """============================================================================
    Tick Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTicks = channel.unary_stream(
                '/world.TickService/StreamTicks',
                request_serializer=world__pb2.StreamTicksRequest.SerializeToString,
                response_deserializer=world__pb2.TickEvent.FromString,
                _registered_method=True)


class TickServiceServicer(object):
    """============================================================================
    Tick Service
    ============================================================================

    """

    def StreamTicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTicks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTicks,
                    request_deserializer=world__pb2.StreamTicksRequest.FromString,
                    response_serializer=world__pb2.TickEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.TickService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.TickService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TickService(object):
    """============================================================================
    Tick Service
    ============================================================================

    """

    @staticmethod
    def StreamTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.TickService/StreamTicks',
            world__pb2.StreamTicksRequest.SerializeToString,
            world__pb2.TickEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EntityDiscoveryServiceStub(object):
    """============================================================================
    Entity Discovery Service (for Runner)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListControllableEntities = channel.unary_unary(
                '/world.EntityDiscoveryService/ListControllableEntities',
                request_serializer=world__pb2.ListControllableEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.ControllableEntitiesResponse.FromString,
                _registered_method=True)


class EntityDiscoveryServiceServicer(object):
    """============================================================================
    Entity Discovery Service (for Runner)
    ============================================================================

    """

    def ListControllableEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntityDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListControllableEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListControllableEntities,
                    request_deserializer=world__pb2.ListControllableEntitiesRequest.FromString,
                    response_serializer=world__pb2.ControllableEntitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.EntityDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.EntityDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntityDiscoveryService(object):
    """============================================================================
    Entity Discovery Service (for Runner)
    ============================================================================

    """

    @staticmethod
    def ListControllableEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.EntityDiscoveryService/ListControllableEntities',
            world__pb2.ListControllableEntitiesRequest.SerializeToString,
            world__pb2.ControllableEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LeaseServiceStub(object):
    """============================================================================
    Lease Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLease = channel.unary_unary(
                '/world.LeaseService/AcquireLease',
                request_serializer=world__pb2.AcquireLeaseRequest.SerializeToString,
                response_deserializer=world__pb2.LeaseResponse.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/world.LeaseService/RenewLease',
                request_serializer=world__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=world__pb2.LeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/world.LeaseService/ReleaseLease',
                request_serializer=world__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=world__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)


class LeaseServiceServicer(object):
    """============================================================================
    Lease Service
    ============================================================================

    """

    def AcquireLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLease,
                    request_deserializer=world__pb2.AcquireLeaseRequest.FromString,
                    response_serializer=world__pb2.LeaseResponse.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=world__pb2.RenewLeaseRequest.FromString,
                    response_serializer=world__pb2.LeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=world__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=world__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.LeaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.LeaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaseService(object):
    """============================================================================
    Lease Service
    ============================================================================

    """

    @staticmethod
    def AcquireLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.LeaseService/AcquireLease',
            world__pb2.AcquireLeaseRequest.SerializeToString,
            world__pb2.LeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.LeaseService/RenewLease',
            world__pb2.RenewLeaseRequest.SerializeToString,
            world__pb2.LeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.LeaseService/ReleaseLease',
            world__pb2.ReleaseLeaseRequest.SerializeToString,
            world__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObservationServiceStub(object):
    """============================================================================
    Observation Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamObservations = channel.unary_stream(
                '/world.ObservationService/StreamObservations',
                request_serializer=world__pb2.StreamObservationsRequest.SerializeToString,
                response_deserializer=world__pb2.Observation.FromString,
                _registered_method=True)


class ObservationServiceServicer(object):
    """============================================================================
    Observation Service
    ============================================================================

    """

    def StreamObservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamObservations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamObservations,
                    request_deserializer=world__pb2.StreamObservationsRequest.FromString,
                    response_serializer=world__pb2.Observation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.ObservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.ObservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservationService(object):
    """============================================================================
    Observation Service
    ============================================================================

    """

    @staticmethod
    def StreamObservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.ObservationService/StreamObservations',
            world__pb2.StreamObservationsRequest.SerializeToString,
            world__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ActionServiceStub(object):
    """============================================================================
    Action Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitIntent = channel.unary_unary(
                '/world.ActionService/SubmitIntent',
                request_serializer=world__pb2.SubmitIntentRequest.SerializeToString,
                response_deserializer=world__pb2.SubmitIntentResponse.FromString,
                _registered_method=True)


class ActionServiceServicer(object):
    """============================================================================
    Action Service
    ============================================================================

    """

    def SubmitIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitIntent,
                    request_deserializer=world__pb2.SubmitIntentRequest.FromString,
                    response_serializer=world__pb2.SubmitIntentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.ActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.ActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionService(object):
    """============================================================================
    Action Service
    ============================================================================

    """

    @staticmethod
    def SubmitIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.ActionService/SubmitIntent',
            world__pb2.SubmitIntentRequest.SerializeToString,
            world__pb2.SubmitIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ViewerServiceStub(object):
    """============================================================================
    Viewer Service (Read-Only)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamViewerEvents = channel.unary_stream(
                '/world.ViewerService/StreamViewerEvents',
                request_serializer=world__pb2.ViewerFilter.SerializeToString,
                response_deserializer=world__pb2.ViewerEvent.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/world.ViewerService/GetSnapshot',
                request_serializer=world__pb2.ViewerFilter.SerializeToString,
                response_deserializer=world__pb2.WorldSnapshot.FromString,
                _registered_method=True)


class ViewerServiceServicer(object):
    """============================================================================
    Viewer Service (Read-Only)
    ============================================================================

    """

    def StreamViewerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamViewerEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamViewerEvents,
                    request_deserializer=world__pb2.ViewerFilter.FromString,
                    response_serializer=world__pb2.ViewerEvent.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=world__pb2.ViewerFilter.FromString,
                    response_serializer=world__pb2.WorldSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.ViewerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.ViewerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ViewerService(object):
    """============================================================================
    Viewer Service (Read-Only)
    ============================================================================

    """

    @staticmethod
    def StreamViewerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.ViewerService/StreamViewerEvents',
            world__pb2.ViewerFilter.SerializeToString,
            world__pb2.ViewerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.ViewerService/GetSnapshot',
            world__pb2.ViewerFilter.SerializeToString,
            world__pb2.WorldSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
